# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Fakebooker-Backend

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: ESLint
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.1.0
      - name: testing
        run: npm test
        env:
          CI: true
